### ISSUE TITLE
Feature request: add stripe link for management

### ISSUE THREAD

**Issue by MomentumV** [makeitlabs/authbackend#12]
On a user's page, have a hyperlink to the customer and/or subscription stripe dashboard page.
Sample data:

cust: cus_XXXxxxXXXXxxx  Stripe link: http://dashboard.stripe.com/customers/cus_XXXxxxXXXXxxx

id: sub_XxXXXXxXXX stripe link: http://dashboard.stripe.com/subscriptions/sub_XxXXXXxXXX

**Comment by bkgoodman** [comment]
Committed to v0.8
