### ISSUE TITLE
feature request: Expand waivers page to allow multiple waiver types 

### ISSUE THREAD

**Issue by MomentumV** [makeitlabs/authbackend#15]
We currently have three waivers with smartwaiver: member, guest, and pro storage bin. Would be nice to have a dropdown selector or search or multiple tabs to support viewing each type of wavier.

**Comment by bkgoodman** [comment]
This won't be too hard - although will require a minor schema change. to add a waiver-type field (v0.8 will require a few minor schema changes - so it will fit nicely with that). We will need to do a complete/fresh waiver wipe-and re-import afterwards. (This is pretty automatic - and will only take about 5 minutes).

XML returned from smartwaiver already has a "waiver_title" filed which contains one of the following:

- MakeIt Labs Waiver
- MakeIt Labs Non-Member Waiver
- Pro Member Storage Bin Agreement

(The third of which seems to have been VERY recently added)

**Comment by bkgoodman** [comment]
Done - and there is a "workspace" waiver, too
